### ISSUE TITLE
PHATE loadings?

### ISSUE THREAD

**Issue by athantas95** [KrishnaswamyLab/PHATE#114]
Hello, I am lately using PHATE for dimensionality reduction and manifold visualization purposes and I would like to retrieve the loadings of PHATE components to the features. I tried to project back from the PHATE space to the features space to get the loadings, like someone would do with PCA and I actually got great correspondence between the PC1 and PHATE1 loadings, which you can see below. \
![PC1_vs_PHATE1_loadings](https://user-images.githubusercontent.com/56867593/170245857-a4ed84ca-d94d-4767-bc7c-17bad0f2a93d.png)
This is not true for PC2 and PHATE2 loadings though. I am also skeptical of the meaning of the projection I applied, because the PHATE data are supposed to be produced with nonlinear transformations. So, I was wondering if I got such correspondence by chance or if there is some recommended way in general to get the loadings. 
On the other hand, I guess that the nonlinearity of the method does not really allow for concepts like loadings since the output is not a linear combination of the features. 
Thanks in advance.

**Comment by athantas95** [comment]
At the same time, the following nature-communications paper has managed to somehow weight the PHATE components onto the features (brain regions) in **Fig.1a,b** but the method for doing that is not clear or actually not shown at all.
[2022 NatComm iyer - Focal neural perturbations reshape lowdimensional trajectories of brain activity supporting cognitive performance.pdf](https://github.com/KrishnaswamyLab/PHATE/files/8770435/2022.NatComm.iyer.-.Focal.neural.perturbations.reshape.lowdimensional.trajectories.of.brain.activity.supporting.cognitive.performance.pdf)

**Comment by kmoon3** [comment]
Good questions. Depending on the complexity of your data, I'm not too surprised that there is some correspondence between PHATE1 and PC1 as those components will likely both be related to the direction of largest variance in the data. But you're right that since PHATE is nonlinear, you shouldn't expect a linear projection to be able to recapitulate it. 

One potential approach to get what you want is to use GRAE, which uses an autoencoder to learn the PHATE embedding. Since it's an autoencoder you can then reconstruct the feature space from the PHATE space. You can find the code here: https://github.com/KevinMoonLab/GRAE

**Comment by athantas95** [comment]
Thanks a lot for the answer! I will have a look :smile:
