### ISSUE TITLE
How would this be applied to non-Biology applications?

### ISSUE THREAD

**Issue by DonaldTsang** [KrishnaswamyLab/PHATE#97]
For those that would like to use it for social media "community detection" (clustering of users) and role-related research, can PHATE be used instead of UMAP and t-SNE, and if so, how?

**Comment by dburkhardt** [comment]
Hi Donald, just like PCA, tSNE, UMAP, and most other conditionality reduction algorithms, you can use PHATE on just about any kind of data. If you look at [Supplementary Figure 3](https://www.nature.com/articles/s41587-019-0336-3/figures/9) and [Supplementary Figure 10](https://www.nature.com/articles/s41587-019-0336-3/figures/16) of the manuscript (see below), you can see PHATE applied to a number of non-biological datasets.

Because you have users in a social network, I imagine your data is naturally represented as a graph. You should be able to pass the graph adjacency matrix using `distance='precomputed'`. [Consult the docs](https://phate.readthedocs.io/en/stable/api.html#module-phate.phate) for more information.

As for "community detection" this is a **clustering** task, not a dimensionality reduction task. For this, you will need to select a graph partitioning algorithm like spectral clustering or louvain.

Hope this helps!

![41587_2019_336_Fig9_ESM](https://user-images.githubusercontent.com/8322751/90407268-51b70b00-e074-11ea-8b15-1105ef91999a.jpg)

![41587_2019_336_Fig16_ESM](https://user-images.githubusercontent.com/8322751/90407226-406dfe80-e074-11ea-901f-c4536ecc2f1d.jpg)

**Comment by DonaldTsang** [comment]
@dburkhardt just to clarify, given the results of a community detection algorithm, how would one represent the data with PHATE?

**Comment by dburkhardt** [comment]
I'm not sure this question makes sense. You could use the partition assignments from any clustering algorithm as a color vector when plotting, but there's no relationship between PHATE and clustering.

To color a PHATE embedding by cluster assignment, see the "Discrete color vector" examples here: 

https://scprep.readthedocs.io/en/stable/examples/scatter.html

**Comment by DonaldTsang** [comment]
@dburkhardt in this case I you are correct, is there a pipeline for data => community detection or clustering => representation through PHATE or others.

**Comment by dburkhardt** [comment]
I would probably checkout our clustering notebooks from our single cell course or the scanpy clustering tutorial if you are looking for introductory clustering resources:

* https://krishnaswamylab.org/workshop
* https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html

**Comment by DonaldTsang** [comment]
Thanks!
